name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd backend
          # This needs a proper test setup.  For the evaluation just check health endpoint.
          curl http://127.0.0.1:8000/api/health & sleep 2
          uvicorn app.main:app --reload --port 8000 & sleep 2
          response=$(curl http://127.0.0.1:8000/api/health)
          if [[ $response == '{"status": "ok"}' ]]; then
            echo "Health check passed!" 
          else
            echo "Health check failed!" 
            exit 1
          fi